### ISSUE TITLE
Can not download openssh_9.7p1-4.debian.tar.xz & openssh_9.7p1-4.dsc

### ISSUE THREAD

**Issue by miaohao0309** [boypt/openssh-deb#1]
--2024-05-29 03:09:03--  http://ftp.us.debian.org/debian//pool/main/o/openssh/openssh_9.7p1-4.debian.tar.xz
Resolving ftp.us.debian.org (ftp.us.debian.org)... 208.80.154.139, 64.50.236.52, 64.50.233.100, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|208.80.154.139|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-29 03:09:04 ERROR 404: Not Found.

--2024-05-29 03:09:04--  http://ftp.us.debian.org/debian//pool/main/o/openssh/openssh_9.7p1-4.dsc
Reusing existing connection to ftp.us.debian.org:80.
HTTP request sent, awaiting response... 404 Not Found
2024-05-29 03:09:04 ERROR 404: Not Found.

**Comment by ChowRex** [comment]
Here is `version.env` should contains:

```
OPENSSLMIR=https://www.openssl.org/source
OPENSSLSRC=openssl-3.0.13.tar.gz
DEBMIRROR=http://mirrors.ustc.edu.cn/debian
OPENSSH_SIDPKG=9.7p1-5
OPENSSHVER=$(echo $OPENSSH_SIDPKG|cut -d- -f1)
```

`openssh_9.7p1-4` should be replaced by `openssh_9.7p1-5`
