### ISSUE TITLE
Unmet build dependencies: dh-sequence-movetousr

### ISSUE THREAD

**Issue by houmenghang** [boypt/openssh-deb#10]
作者，您好：

我在用您的脚本编译的过程中总是碰到这个问题，能烦请您帮忙看看么
dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-sequence-movetousr
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Aborted, error 3 in command: env DEB_BUILD_OPTIONS=nocheck DEB_BUILD_PROFILES=pkg.openssh.nognome dpkg-buildpackage --no-sign -rfakeroot -b

**Comment by boypt** [comment]
use `./compile.sh` instead of `dpkg-source --before-build .`

`dh-sequence-movetousr` is provided by a newer version `debhelper`, which I put it in `builddeps` dir. the script will install it, or you could try install these deb files inside.
