### ISSUE TITLE
When I was running ./compile. sh, this error occurred

### ISSUE THREAD

**Issue by zongxj** [boypt/openssh-deb#3]
<img width="1504" alt="image" src="https://github.com/boypt/openssh-deb/assets/29390707/f192e493-75cf-4a95-8224-5913577f8efd">

**Comment by boypt** [comment]
it's likely you're running it on quite an old version of deb/ub system, I tried that on a ubuntu 18.04 too, but too much issue about dependencies. support dropped.

**Comment by hetaoos** [comment]
ubuntu 22.04.4
```
dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-sequence-movetousr
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

```

**Comment by boypt** [comment]
Well that shouldn't happen then, the script would install a newer version of `dh-sequence-movetousr` deb, see https://github.com/boypt/openssh-deb/blob/c9f6b2770650663b653c63fa180deac8e22fdf24/compile.sh#L42-L43

You may try install the deb files inside `builddep` .
