### ISSUE TITLE
dpkg-checkbuilddeps: error: Unmet build dependencies: libpam0g-dev | libpam-dev libselinux1-dev libwrap0-dev | libwrap-dev pkgconf

### ISSUE THREAD

**Issue by camuselliot** [boypt/openssh-deb#7]
老师 ： 您好，我执行  ./compile.sh  后面就报错了这个  我的os 系统是 ubuntu 22.04 
dpkg-checkbuilddeps: error: Unmet build dependencies: libpam0g-dev | libpam-dev libselinux1-dev libwrap0-dev | libwrap-dev pkgconf
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Aborted, error 3 in command: env DEB_BUILD_OPTIONS=nocheck DEB_BUILD_PROFILES=pkg.openssh.nognome dpkg-buildpackage --no-sign -rfakeroot -b

**Comment by camuselliot** [comment]
cat version.env
OPENSSLMIR=https://www.openssl.org/source/
OPENSSLSRC=openssl-3.0.14.tar.gz
DEBMIRROR=http://ftp.us.debian.org/debian/
OPENSSH_SIDPKG=9.7p1-7
OPENSSHVER=$(echo $OPENSSH_SIDPKG|cut -d- -f1)

**Comment by boypt** [comment]
Direct Build
# Install Dependencies
sudo apt install pkgconf build-essential fakeroot \
    dpkg-dev debhelper debhelper-compat dh-exec dh-runit \
    libkrb5-dev libpam0g-dev libwrap0-dev \
    libaudit-dev libedit-dev libfido2-dev \
    libgtk-3-dev libselinux1-dev libsystemd-dev \
    libcbor-dev

# pull source
./pullsrc.sh

# direct build
./compile.sh

**Comment by camuselliot** [comment]
thank you so much
